# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_stack_book_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
