# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets_app', '0002_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='dojo_secrets_app.User'),
        ),
    ]
